version: '3.8'

services:
  # Goバックエンド開発環境
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
    command: go run main.go

  # Node.js開発環境（Tauri用）
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - .:/app
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev

volumes:
  go-modules:
  node-modules:
